class Test {
  static const Map<String, List<Map<String, dynamic>>> allTypes = {
    "Html": [
      {
        'id': 'basic',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Tags', 'elements', 'attributes', 'structure'],
      },
      {
        'id': 'forms',
        'title': 'Forms',
        'tier': 'free',
        'topics': ['Form elements', 'inputs', 'buttons', 'validation'],
      },
      {
        'id': 'html5',
        'title': 'HTML5 New Features',
        'tier': 'free',
        'topics': ['Semantic tags', 'multimedia (audio/video)', 'canvas'],
      },
      {
        'id': 'tables',
        'title': 'Tables',
        'tier': 'free',
        'topics': ['Table structure', 'headers', 'captions', 'colspan/rowspan'],
      },
      {
        'id': 'lists',
        'title': 'Lists',
        'tier': 'free',
        'topics': ['Ordered', 'unordered', 'description lists'],
      },
      {
        'id': 'links',
        'title': 'Links & Navigation',
        'tier': 'vip',
        'topics': ['Anchor tags', 'navigation menus'],
      },
      {
        'id': 'media',
        'title': 'Media Elements',
        'tier': 'vip',
        'topics': ['Embedding videos', 'audio', 'images'],
      },
    ],
    "Css": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Selectors', 'properties', 'values', 'syntax'],
      },
      {
        'id': 'box',
        'title': 'Box Model',
        'tier': 'free',
        'topics': ['Margin', 'border', 'padding', 'content'],
      },
      {
        'id': 'position',
        'title': 'Positioning',
        'tier': 'free',
        'topics': ['Static', 'relative', 'absolute', 'fixed', 'sticky'],
      },
      {
        'id': 'flex',
        'title': 'Flexbox & Grid',
        'tier': 'free',
        'topics': [
          'Containers',
          'flex items',
          'alignment',
          'spacing',
          'Grid containers',
          'tracks',
          'areas',
        ],
      },
      {
        'id': 'font',
        'title': 'Typography',
        'tier': 'free',
        'topics': ['Fonts', 'text alignment', 'line height', 'letter spacing'],
      },
      {
        'id': 'color',
        'title': 'Colors and Backgrounds',
        'tier': 'free',
        'topics': ['Color formats', 'gradients', 'background images'],
      },
      {
        'id': 'anim',
        'title': 'Transitions & Animations',
        'tier': 'vip',
        'topics': ['Keyframes', 'easing', 'delays'],
      },
      {
        'id': 'query',
        'title': 'Media Queries',
        'tier': 'vip',
        'topics': ['Responsive design', 'breakpoints'],
      },
      {
        'id': 'pseudo',
        'title': 'Pseudo-classes & Elements',
        'tier': 'vip',
        'topics': ['Hover effects', 'first-child', '::before', '::after'],
      },
    ],
    "Javascript": [
      {
        'id': 'basic',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Variables', 'data types', 'operators', 'syntax'],
      },
      {
        'id': 'control',
        'title': 'Control Structures',
        'tier': 'free',
        'topics': [
          'If-else',
          'switch-case',
          '"loops (for',
          'while',
          'do-while)"',
        ],
      },
      {
        'id': 'func',
        'title': 'Functions',
        'tier': 'free',
        'topics': [
          'Function declarations',
          'expressions',
          'arrow functions',
          'scopes',
        ],
      },
      {
        'id': 'dom',
        'title': 'DOM Manipulation',
        'tier': 'free',
        'topics': [
          'Selecting elements',
          'event handling',
          'modifying HTML/CSS',
        ],
      },
      {
        'id': 'events',
        'title': 'Events',
        'tier': 'free',
        'topics': [
          'Event listeners',
          'bubbling',
          'delegation',
          'default actions',
        ],
      },
      {
        'id': 'obj',
        'title': 'Objects and Arrays',
        'tier': 'free',
        'topics': ['Creation', 'methods', 'destructuring'],
      },
      {
        'id': 'es6',
        'title': 'ES6+ Features',
        'tier': 'vip',
        'topics': [
          'Let/const',
          'template literals',
          'spread/rest operators',
          'modules',
        ],
      },
      {
        'id': 'async',
        'title': 'Asynchronous JavaScript',
        'tier': 'vip',
        'topics': ['Callbacks', 'promises', 'async/await'],
      },
      {
        'id': 'error',
        'title': 'Error Handling',
        'tier': 'vip',
        'topics': ['Try-catch', 'custom errors', 'debugging'],
      },
      {
        'id': 'api',
        'title': 'APIs',
        'tier': 'vip',
        'topics': ['Fetch API', 'local storage', 'geolocation'],
      },
    ],
    "UI UX Tools": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          'UI/UX principles',
          'wireframing basics',
          'prototyping fundamentals',
          'user research',
        ],
      },
      {
        'id': 'figma',
        'title': 'Figma',
        'tier': 'free',
        'topics': [
          'Interface design',
          'collaboration features',
          'plugins',
          'prototyping in Figma',
        ],
      },
      {
        'id': 'adobexd',
        'title': 'Adobe XD',
        'tier': 'free',
        'topics': [
          'Vector editing',
          'interactive prototypes',
          'handoff to developers',
          'auto-layout',
        ],
      },
      {
        'id': 'sketch',
        'title': 'Sketch',
        'tier': 'free',
        'topics': ['App design', 'components', 'symbols', 'team libraries'],
      },
      {
        'id': 'invision',
        'title': 'InVision Studio',
        'tier': 'vip',
        'topics': [
          'Interactive prototypes',
          'user testing',
          'animations',
          'version history',
        ],
      },
      {
        'id': 'prototyping',
        'title': 'Prototyping Tools',
        'tier': 'vip',
        'topics': [
          'High-fidelity prototypes',
          'user flows',
          'micro-interactions',
          'accessibility tools',
        ],
      },
      {
        'id': 'wireframing',
        'title': 'Wireframing & Mockups',
        'tier': 'vip',
        'topics': [
          'Low-fidelity sketches',
          'grid systems',
          'color palettes',
          'typography choices',
        ],
      },
    ],
    "React": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          'Create React App',
          'JSX syntax',
          'rendering elements',
          'functional components',
        ],
      },
      {
        'id': 'components',
        'title': 'Components',
        'tier': 'free',
        'topics': [
          'Class components',
          'functional components',
          'props passing',
          'children',
        ],
      },
      {
        'id': 'state',
        'title': 'State & Props',
        'tier': 'free',
        'topics': [
          'useState',
          'lifecycle methods',
          'state updates',
          'conditional rendering',
        ],
      },
      {
        'id': 'hooks',
        'title': 'Hooks',
        'tier': 'free',
        'topics': [
          'Prop types',
          'default props',
          'prop drilling',
          'controlled components',
        ],
      },
      {
        'id': 'routing',
        'title': 'Routing',
        'tier': 'vip',
        'topics': ['useEffect', 'useContext', 'custom hooks', 'useReducer'],
      },
      {
        'id': 'redux',
        'title': 'State Management (Redux)',
        'tier': 'vip',
        'topics': [
          'React Router DOM',
          'nested routes',
          'route guards',
          'lazy loading',
        ],
      },
      {
        'id': 'context',
        'title': 'Context API',
        'tier': 'vip',
        'topics': ['Actions', 'reducers', 'middleware', 'thunk/saga'],
      },
      {
        'id': 'performance',
        'title': 'Performance Optimization',
        'tier': 'vip',
        'topics': [
          'Providers',
          'consumers',
          'context with hooks',
          'multiple contexts',
        ],
      },
      {
        'id': 'testing',
        'title': 'Testing',
        'tier': 'vip',
        'topics': [
          'Memoization',
          'pure components',
          'code splitting',
          'profiler',
        ],
      },
    ],
    "Vue js": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          'Vue instance',
          'data binding',
          '"directives (v-bind',
          'v-model)"',
          'computed properties',
        ],
      },
      {
        'id': 'components',
        'title': 'Components',
        'tier': 'free',
        'topics': ['Single-file components', 'props', 'slots', 'emits'],
      },
      {
        'id': 'directives',
        'title': 'Directives',
        'tier': 'free',
        'topics': ['v-if/v-else', 'v-for', 'v-on', 'custom directives'],
      },
      {
        'id': 'reactivity',
        'title': 'Reactivity System',
        'tier': 'free',
        'topics': [
          'Reactive data',
          'watchers',
          'computed vs methods',
          'reactivity caveats',
        ],
      },
      {
        'id': 'routing',
        'title': 'Vue Router',
        'tier': 'vip',
        'topics': [
          'Route definitions',
          'navigation guards',
          'dynamic routes',
          'lazy loading',
        ],
      },
      {
        'id': 'vuex',
        'title': 'State Management (Vuex)',
        'tier': 'vip',
        'topics': ['Modules', 'mutations', 'actions', 'getters'],
      },
      {
        'id': 'composition',
        'title': 'Composition API',
        'tier': 'vip',
        'topics': [
          'Setup function',
          'ref/reactive',
          'lifecycle hooks',
          'provide/inject',
        ],
      },
      {
        'id': 'ssr',
        'title': 'Server-Side Rendering',
        'tier': 'vip',
        'topics': [
          'Nuxt.js',
          'universal rendering',
          'hydration',
          'static generation',
        ],
      },
    ],
    "Angular": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Angular CLI', 'modules', 'components', 'data binding'],
      },
      {
        'id': 'components',
        'title': 'Components & Templates',
        'tier': 'free',
        'topics': [
          'Templates',
          'interpolation',
          'property binding',
          'event binding',
        ],
      },
      {
        'id': 'directives',
        'title': 'Directives',
        'tier': 'free',
        'topics': [
          '"Structural (*ngIf',
          '*ngFor)"',
          'attribute',
          'custom directives',
        ],
      },
      {
        'id': 'services',
        'title': 'Services & Dependency Injection',
        'tier': 'free',
        'topics': [
          'Injectors',
          'providers',
          'singleton services',
          'HTTP client',
        ],
      },
      {
        'id': 'routing',
        'title': 'Routing',
        'tier': 'vip',
        'topics': [
          'Router module',
          'route params',
          'child routes',
          'resolvers',
        ],
      },
      {
        'id': 'forms',
        'title': 'Forms',
        'tier': 'vip',
        'topics': [
          'Template-driven',
          'reactive forms',
          'validators',
          'form groups',
        ],
      },
      {
        'id': 'rxjs',
        'title': 'RxJS & Observables',
        'tier': 'vip',
        'topics': [
          'Operators',
          'subjects',
          'subscription management',
          'async pipe',
        ],
      },
      {
        'id': 'ngrx',
        'title': 'State Management (NgRx)',
        'tier': 'vip',
        'topics': ['Store', 'effects', 'selectors', 'entity adapter'],
      },
      {
        'id': 'testing',
        'title': 'Testing',
        'tier': 'vip',
        'topics': [
          'Karma',
          'Jasmine',
          'component testing',
          'e2e with Protractor',
        ],
      },
    ],
    "Svelte": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          'Svelte CLI',
          'components',
          'reactive declarations',
          'bindings',
        ],
      },
      {
        'id': 'components',
        'title': 'Components',
        'tier': 'free',
        'topics': ['Props', 'slots', 'events', 'context API'],
      },
      {
        'id': 'reactivity',
        'title': 'Reactivity',
        'tier': 'free',
        'topics': ['\$: syntax', 'stores', 'derived stores', 'tweened/motion'],
      },
      {
        'id': 'stores',
        'title': 'Stores',
        'tier': 'free',
        'topics': [
          'Writable',
          'readable',
          'store subscriptions',
          'auto-subscriptions',
        ],
      },
      {
        'id': 'transitions',
        'title': 'Transitions & Animations',
        'tier': 'vip',
        'topics': [
          'Css transitions',
          'in/out',
          'spring physics',
          'custom transitions',
        ],
      },
      {
        'id': 'routing',
        'title': 'Routing',
        'tier': 'vip',
        'topics': ['Svelte Navigator', 'page transitions', 'route params'],
      },
      {
        'id': 'sapper',
        'title': 'Sapper/SvelteKit',
        'tier': 'vip',
        'topics': [
          'Framework features',
          'static site generation',
          'server-side rendering',
        ],
      },
    ],
    "Server-Side Languages": [
      {
        'id': 'node',
        'title': 'Node.js',
        'tier': 'free',
        'topics': [
          'Runtime environment',
          'modules',
          'async programming',
          'event loop',
        ],
      },
      {
        'id': 'python',
        'title': 'Python',
        'tier': 'free',
        'topics': [
          'Syntax',
          'libraries (Flask/Django)',
          'virtual environments',
          'decorators',
        ],
      },
      {
        'id': 'java',
        'title': 'Java',
        'tier': 'free',
        'topics': ['OOP', 'Spring framework', 'lambdas', 'streams'],
      },
      {
        'id': 'php',
        'title': 'PHP',
        'tier': 'free',
        'topics': ['Syntax', 'frameworks (Laravel)', 'sessions', 'databases'],
      },
      {
        'id': 'ruby',
        'title': 'Ruby',
        'tier': 'vip',
        'topics': ['Syntax', 'Rails', 'gems', 'Active Record'],
      },
      {
        'id': 'go',
        'title': 'Go',
        'tier': 'vip',
        'topics': ['Concurrency', 'goroutines', 'channels', 'error handling'],
      },
      {
        'id': 'dotnet',
        'title': '.NET',
        'tier': 'vip',
        'topics': ['C# syntax', 'ASP.NET', 'Entity Framework', 'Razor pages'],
      },
    ],
    "APIs": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['HTTP methods', 'status codes', 'headers', 'endpoints'],
      },
      {
        'id': 'rest',
        'title': 'RESTful APIs',
        'tier': 'free',
        'topics': ['Resources', 'CRUD operations', 'HATEOAS', 'pagination'],
      },
      {
        'id': 'graphql',
        'title': 'GraphQL',
        'tier': 'free',
        'topics': ['Queries', 'mutations', 'resolvers', 'schemas'],
      },
      {
        'id': 'design',
        'title': 'API Design',
        'tier': 'free',
        'topics': [
          'Best practices',
          'naming conventions',
          'error handling',
          'documentation (Swagger)',
        ],
      },
      {
        'id': 'security',
        'title': 'API Security',
        'tier': 'vip',
        'topics': ['API keys', 'tokens', 'rate limiting', 'CORS'],
      },
      {
        'id': 'rate',
        'title': 'Rate Limiting & Throttling',
        'tier': 'vip',
        'topics': ['Algorithms', 'implementation', 'bypassing limits'],
      },
      {
        'id': 'versioning',
        'title': 'Versioning',
        'tier': 'vip',
        'topics': [
          'Semantic versioning',
          'deprecation',
          'backward compatibility',
        ],
      },
    ],
    "Authentication & Authorization": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['User sessions', 'password hashing', 'tokens vs sessions'],
      },
      {
        'id': 'jwt',
        'title': 'JWT',
        'tier': 'free',
        'topics': [
          'Token structure',
          'signing',
          'verification',
          'refresh tokens',
        ],
      },
      {
        'id': 'oauth',
        'title': 'OAuth',
        'tier': 'free',
        'topics': [
          '"Flows (authorization code',
          'implicit)"',
          'scopes',
          '"providers (Google',
          'Facebook)"',
        ],
      },
      {
        'id': 'sessions',
        'title': 'Sessions & Cookies',
        'tier': 'free',
        'topics': ['State management', 'secure cookies', 'session fixation'],
      },
      {
        'id': 'rbac',
        'title': 'Role-Based Access Control',
        'tier': 'vip',
        'topics': ['Permissions', 'roles', 'ACLs', 'implementation'],
      },
      {
        'id': 'mfa',
        'title': 'Multi-Factor Authentication',
        'tier': 'vip',
        'topics': ['Setup', 'TOTP', 'biometrics', 'recovery codes'],
      },
      {
        'id': 'sso',
        'title': 'Single Sign-On',
        'tier': 'vip',
        'topics': [
          'SAML',
          'OpenID Connect',
          'federation',
          'identity providers',
        ],
      },
    ],
    "Web Servers": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['HTTP/HTTPS', 'virtual hosts', 'reverse proxy', 'caching'],
      },
      {
        'id': 'nginx',
        'title': 'Nginx',
        'tier': 'free',
        'topics': [
          'Configuration files',
          'modules',
          'server blocks',
          'SSL setup',
        ],
      },
      {
        'id': 'apache',
        'title': 'Apache',
        'tier': 'free',
        'topics': ['Directives', 'modules', '.htaccess', 'rewrites'],
      },
      {
        'id': 'iis',
        'title': 'IIS',
        'tier': 'vip',
        'topics': ['Sites', 'application pools', 'authentication modes'],
      },
      {
        'id': 'config',
        'title': 'Configuration & Optimization',
        'tier': 'vip',
        'topics': ['Performance tuning', 'gzip compression', 'keep-alive'],
      },
      {
        'id': 'load',
        'title': 'Load Balancing',
        'tier': 'vip',
        'topics': ['Round-robin', 'health checks', 'sticky sessions'],
      },
    ],
    "Express js": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['App setup', 'routes', 'request/response objects'],
      },
      {
        'id': 'routing',
        'title': 'Routing',
        'tier': 'free',
        'topics': ['GET/POST', 'params', 'query strings', 'route handlers'],
      },
      {
        'id': 'middleware',
        'title': 'Middleware',
        'tier': 'free',
        'topics': [
          'Custom middleware',
          'error middleware',
          '"third-party (body-parser',
          'cors)"',
        ],
      },
      {
        'id': 'templates',
        'title': 'Template Engines',
        'tier': 'free',
        'topics': ['EJS/Pug', 'rendering', 'partials', 'locals'],
      },
      {
        'id': 'error',
        'title': 'Error Handling',
        'tier': 'vip',
        'topics': ['404 handling', 'async errors', 'global catch'],
      },
      {
        'id': 'security',
        'title': 'Security Best Practices',
        'tier': 'vip',
        'topics': ['Helmet', 'input validation', 'rate limiting'],
      },
      {
        'id': 'testing',
        'title': 'Testing',
        'tier': 'vip',
        'topics': ['Mocha/Chai', 'supertest', 'unit/integration tests'],
      },
    ],
    "Django": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Project structure', 'apps', 'settings', 'URLs'],
      },
      {
        'id': 'models',
        'title': 'Models',
        'tier': 'free',
        'topics': ['Fields', 'migrations', 'querysets', 'relationships'],
      },
      {
        'id': 'views',
        'title': 'Views',
        'tier': 'free',
        'topics': ['Class-based', 'function-based', 'generic views'],
      },
      {
        'id': 'templates',
        'title': 'Templates',
        'tier': 'free',
        'topics': ['Inheritance', 'context', 'static files', 'includes'],
      },
      {
        'id': 'forms',
        'title': 'Forms',
        'tier': 'vip',
        'topics': ['Model forms', 'formsets', 'validation', 'widgets'],
      },
      {
        'id': 'admin',
        'title': 'Admin Interface',
        'tier': 'vip',
        'topics': ['Customization', 'model admin', 'inlines', 'actions'],
      },
      {
        'id': 'rest',
        'title': 'Django REST Framework',
        'tier': 'vip',
        'topics': ['Serializers', 'viewsets', 'routers', 'authentication'],
      },
      {
        'id': 'security',
        'title': 'Security',
        'tier': 'vip',
        'topics': ['CSRF', 'permissions', 'middleware'],
      },
    ],
    "Spring Boot": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Starters', 'application properties', 'embedded server'],
      },
      {
        'id': 'controllers',
        'title': 'Controllers',
        'tier': 'free',
        'topics': ['REST controllers', 'request mapping', 'path variables'],
      },
      {
        'id': 'services',
        'title': 'Services',
        'tier': 'free',
        'topics': ['Service layer', 'autowiring', 'transaction management'],
      },
      {
        'id': 'data',
        'title': 'Spring Data',
        'tier': 'free',
        'topics': ['JPA repositories', 'entities', 'queries'],
      },
      {
        'id': 'security',
        'title': 'Spring Security',
        'tier': 'vip',
        'topics': ['OAuth2', 'JWT integration', 'method security'],
      },
      {
        'id': 'boot',
        'title': 'Auto-Configuration',
        'tier': 'vip',
        'topics': ['Profiles', 'actuators', 'custom starters'],
      },
      {
        'id': 'testing',
        'title': 'Testing',
        'tier': 'vip',
        'topics': ['Spring Test', 'MockMVC', 'integration tests'],
      },
      {
        'id': 'micro',
        'title': 'Microservices',
        'tier': 'vip',
        'topics': ['Eureka', 'Feign clients', 'circuit breakers'],
      },
    ],
    "Laravel": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Artisan', 'routes', 'middleware', 'controllers'],
      },
      {
        'id': 'routing',
        'title': 'Routing',
        'tier': 'free',
        'topics': ['Resource routes', 'route model binding', 'named routes'],
      },
      {
        'id': 'controllers',
        'title': 'Controllers',
        'tier': 'free',
        'topics': ['Actions', 'requests', 'responses', 'views'],
      },
      {
        'id': 'eloquent',
        'title': 'Eloquent ORM',
        'tier': 'free',
        'topics': ['Models', 'relationships', 'scopes', 'accessors/mutators'],
      },
      {
        'id': 'blade',
        'title': 'Blade Templates',
        'tier': 'vip',
        'topics': ['Directives', 'components', 'layouts', 'slots'],
      },
      {
        'id': 'auth',
        'title': 'Authentication',
        'tier': 'vip',
        'topics': ['Sanctum', 'Passport', 'gates', 'policies'],
      },
      {
        'id': 'testing',
        'title': 'Testing',
        'tier': 'vip',
        'topics': ['PHPUnit', 'dusk', 'mocking'],
      },
      {
        'id': 'queues',
        'title': 'Queues & Jobs',
        'tier': 'vip',
        'topics': ['Horizon', 'task scheduling', 'events'],
      },
    ],
    "SQL Databases": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['DDL', 'DML', 'data types', 'constraints'],
      },
      {
        'id': 'queries',
        'title': 'Queries',
        'tier': 'free',
        'topics': ['SELECT', 'WHERE', 'GROUP BY', 'HAVING', 'ORDER BY'],
      },
      {
        'id': 'joins',
        'title': 'Joins',
        'tier': 'free',
        'topics': ['INNER', 'LEFT/RIGHT', 'FULL', 'CROSS', 'self-joins'],
      },
      {
        'id': 'indexes',
        'title': 'Indexes',
        'tier': 'free',
        'topics': ['Clustered', 'non-clustered', 'covering', 'index tuning'],
      },
      {
        'id': 'transactions',
        'title': 'Transactions',
        'tier': 'vip',
        'topics': ['ACID properties', 'isolation levels', 'commits/rollbacks'],
      },
      {
        'id': 'optimization',
        'title': 'Optimization',
        'tier': 'vip',
        'topics': ['Query plans', 'partitioning', 'sharding'],
      },
      {
        'id': 'postgres',
        'title': 'PostgreSQL Specifics',
        'tier': 'vip',
        'topics': ['Triggers', 'functions', 'JSON support'],
      },
      {
        'id': 'mysql',
        'title': 'MySQL Specifics',
        'tier': 'vip',
        'topics': ['InnoDB', 'stored procedures', 'views'],
      },
    ],
    "NoSQL Databases": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          'CAP theorem',
          'eventual consistency',
          'schemas vs schema-less',
        ],
      },
      {
        'id': 'document',
        'title': 'Document Databases (MongoDB)',
        'tier': 'free',
        'topics': [
          'Collections',
          'documents',
          'aggregation pipeline',
          'indexes',
        ],
      },
      {
        'id': 'keyvalue',
        'title': 'Key-Value Stores (Redis)',
        'tier': 'free',
        'topics': ['Sets', 'hashes', 'lists', 'pub/sub', 'expiration'],
      },
      {
        'id': 'graph',
        'title': 'Graph Databases (Neo4j)',
        'tier': 'free',
        'topics': ['Nodes', 'relationships', 'Cypher queries', 'properties'],
      },
      {
        'id': 'column',
        'title': 'Column-Family Stores (Cassandra)',
        'tier': 'vip',
        'topics': [
          'Wide columns',
          'consistency levels',
          'CQL',
          'materialized views',
        ],
      },
      {
        'id': 'querying',
        'title': 'Querying & Indexing',
        'tier': 'vip',
        'topics': ['Aggregation frameworks', 'secondary indexes'],
      },
      {
        'id': 'scaling',
        'title': 'Scaling',
        'tier': 'vip',
        'topics': ['Horizontal scaling', 'replication', 'sharding'],
      },
    ],
    "ORM and ODM": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          'Mapping objects to tables',
          'lazy/eager loading',
          'caching',
        ],
      },
      {
        'id': 'sqlalchemy',
        'title': 'SQLAlchemy',
        'tier': 'free',
        'topics': ['Sessions', 'queries', 'relationships', 'transactions'],
      },
      {
        'id': 'hibernate',
        'title': 'Hibernate',
        'tier': 'free',
        'topics': ['Entities', 'annotations', 'criteria API', 'JPQL'],
      },
      {
        'id': 'mongoose',
        'title': 'Mongoose',
        'tier': 'free',
        'topics': ['Schemas', 'models', 'populate', 'virtuals'],
      },
      {
        'id': 'prisma',
        'title': 'Prisma',
        'tier': 'vip',
        'topics': ['Client generation', 'migrations', 'transactions'],
      },
      {
        'id': 'mapping',
        'title': 'Mapping & Relationships',
        'tier': 'vip',
        'topics': ['One-to-many', 'many-to-many', 'inheritance mapping'],
      },
      {
        'id': 'queries',
        'title': 'Query Building',
        'tier': 'vip',
        'topics': ['Builders', 'joins', 'subqueries'],
      },
    ],
    "Database Design": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Entities', 'attributes', 'relationships', 'cardinality'],
      },
      {
        'id': 'normalization',
        'title': 'Normalization',
        'tier': 'free',
        'topics': ['1NF to 5NF', 'denormalization trade-offs'],
      },
      {
        'id': 'erd',
        'title': 'ER Diagrams',
        'tier': 'free',
        'topics': ['Entities', 'relationships', ' crow\'s foot notation'],
      },
      {
        'id': 'keys',
        'title': 'Keys & Constraints',
        'tier': 'free',
        'topics': ['Primary', 'foreign', 'unique', 'check constraints'],
      },
      {
        'id': 'schemas',
        'title': 'Schemas',
        'tier': 'vip',
        'topics': ['Star/snowflake', 'fact/dimension tables'],
      },
      {
        'id': 'partitioning',
        'title': 'Partitioning',
        'tier': 'vip',
        'topics': ['Range', 'hash', 'list partitioning'],
      },
      {
        'id': 'migration',
        'title': 'Migrations',
        'tier': 'vip',
        'topics': ['"Tools (Alembic', 'Flyway)"', 'version control'],
      },
    ],
    "Git": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Init', 'add', 'commit', 'status', 'log'],
      },
      {
        'id': 'branching',
        'title': 'Branching',
        'tier': 'free',
        'topics': ['Create', 'switch', 'merge conflicts', 'delete'],
      },
      {
        'id': 'merging',
        'title': 'Merging & Rebasing',
        'tier': 'free',
        'topics': ['Fast-forward', 'three-way merge', 'rebase vs merge'],
      },
      {
        'id': 'remotes',
        'title': 'Remotes',
        'tier': 'free',
        'topics': ['Push', 'pull', 'fetch', 'remote tracking'],
      },
      {
        'id': 'stash',
        'title': 'Stashing & Cherry-Picking',
        'tier': 'vip',
        'topics': ['Apply', 'pop', 'selective staging'],
      },
      {
        'id': 'hooks',
        'title': 'Hooks',
        'tier': 'vip',
        'topics': ['Pre-commit', 'post-merge', 'client/server hooks'],
      },
      {
        'id': 'advanced',
        'title': 'Advanced Workflows',
        'tier': 'vip',
        'topics': ['Submodules', 'gitflow', 'revert/reset'],
      },
    ],
    "Collaboration Platforms": [
      {
        'id': 'github',
        'title': 'GitHub',
        'tier': 'free',
        'topics': ['Repos', 'forks', 'stars', 'actions'],
      },
      {
        'id': 'gitlab',
        'title': 'GitLab',
        'tier': 'free',
        'topics': ['Pipelines', 'merge requests', 'wikis'],
      },
      {
        'id': 'bitbucket',
        'title': 'Bitbucket',
        'tier': 'free',
        'topics': ['Pipelines', 'pull requests', 'stash'],
      },
      {
        'id': 'pr',
        'title': 'Pull Requests',
        'tier': 'free',
        'topics': ['Reviews', 'approvals', 'comments', 'branches'],
      },
      {
        'id': 'issues',
        'title': 'Issues & Project Management',
        'tier': 'vip',
        'topics': ['Tracking', 'milestones', 'labels', 'assignees'],
      },
      {
        'id': 'ci',
        'title': 'CI Integration',
        'tier': 'vip',
        'topics': ['Runners', 'variables', 'artifacts'],
      },
    ],
    "Containerization": [
      {
        'id': 'docker',
        'title': 'Docker Basics',
        'tier': 'free',
        'topics': [
          'Installation',
          '"commands (run',
          'build',
          'exec)"',
          'Dockerfile',
        ],
      },
      {
        'id': 'images',
        'title': 'Images & Containers',
        'tier': 'free',
        'topics': ['Layers', 'tags', 'registries', 'multi-stage builds'],
      },
      {
        'id': 'compose',
        'title': 'Docker Compose',
        'tier': 'free',
        'topics': ['Services', 'volumes', 'networks', 'YAML syntax'],
      },
      {
        'id': 'volumes',
        'title': 'Volumes & Networks',
        'tier': 'free',
        'topics': ['Persistence', 'bind mounts', 'named volumes'],
      },
      {
        'id': 'kubernetes',
        'title': 'Kubernetes Basics',
        'tier': 'vip',
        'topics': ['Pods', 'deployments', 'services', 'kubectl'],
      },
      {
        'id': 'orchestration',
        'title': 'Orchestration',
        'tier': 'vip',
        'topics': ['Helm', 'operators', 'scaling'],
      },
      {
        'id': 'security',
        'title': 'Security',
        'tier': 'vip',
        'topics': ['Secrets', 'resource limits', 'vulnerability scanning'],
      },
    ],
    "CI CD": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Pipelines', 'stages', 'jobs', 'artifacts'],
      },
      {
        'id': 'jenkins',
        'title': 'Jenkins',
        'tier': 'free',
        'topics': ['Jobs', 'agents', 'plugins', 'blue ocean'],
      },
      {
        'id': 'githubactions',
        'title': 'GitHub Actions',
        'tier': 'free',
        'topics': ['Workflows', 'steps', 'triggers', 'secrets'],
      },
      {
        'id': 'gitlabci',
        'title': 'GitLab CI',
        'tier': 'free',
        'topics': ['YAML config', 'runners', 'caching'],
      },
      {
        'id': 'pipelines',
        'title': 'Pipelines',
        'tier': 'vip',
        'topics': ['Build', 'test', 'deploy stages', 'parallel execution'],
      },
      {
        'id': 'deployment',
        'title': 'Deployment Strategies',
        'tier': 'vip',
        'topics': ['Blue-green', 'canary', 'rolling updates'],
      },
      {
        'id': 'monitoring',
        'title': 'Monitoring',
        'tier': 'vip',
        'topics': ['Integration with monitoring', 'failure notifications'],
      },
    ],
    "Cloud Platforms": [
      {
        'id': 'aws',
        'title': 'AWS',
        'tier': 'free',
        'topics': ['EC2', 'S3', 'Lambda', 'RDS'],
      },
      {
        'id': 'azure',
        'title': 'Azure',
        'tier': 'free',
        'topics': [
          'Virtual Machines',
          'Blob Storage',
          'Functions',
          'SQL Database',
        ],
      },
      {
        'id': 'gcp',
        'title': 'Google Cloud Platform',
        'tier': 'free',
        'topics': [
          'Compute Engine',
          'Cloud Storage',
          'Cloud Functions',
          'BigQuery',
        ],
      },
      {
        'id': 'services',
        'title': 'Core Services',
        'tier': 'free',
        'topics': ['IAM', 'VPCs', 'load balancers', 'auto-scaling groups'],
      },
      {
        'id': 'serverless',
        'title': 'Serverless',
        'tier': 'vip',
        'topics': ['FaaS', 'event-driven', 'API management'],
      },
      {
        'id': 'storage',
        'title': 'Storage & Databases',
        'tier': 'vip',
        'topics': ['Object storage', 'managed databases', 'CDNs'],
      },
      {
        'id': 'security',
        'title': 'Security & Compliance',
        'tier': 'vip',
        'topics': ['Roles', 'policies', 'compliance standards'],
      },
    ],
    "Monitoring & Scaling": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Metrics', 'logs', 'traces', 'alerts'],
      },
      {
        'id': 'prometheus',
        'title': 'Prometheus',
        'tier': 'free',
        'topics': ['Scraping', 'exporters', 'queries (PromQL)'],
      },
      {
        'id': 'grafana',
        'title': 'Grafana',
        'tier': 'free',
        'topics': ['Dashboards', 'panels', 'data sources', 'alerting'],
      },
      {
        'id': 'logs',
        'title': 'Logging (ELK Stack)',
        'tier': 'free',
        'topics': ['Elasticsearch', 'Logstash', 'Kibana', 'beats'],
      },
      {
        'id': 'autoscaling',
        'title': 'Auto-Scaling',
        'tier': 'vip',
        'topics': ['Horizontal/vertical', 'auto-scaling groups', 'policies'],
      },
      {
        'id': 'alerting',
        'title': 'Alerting',
        'tier': 'vip',
        'topics': ['Rules', 'notifications', 'integrations'],
      },
      {
        'id': 'performance',
        'title': 'Performance Metrics',
        'tier': 'vip',
        'topics': ['CPU/memory', 'latency', 'error rates', 'custom metrics'],
      },
    ],
    "Unit Testing": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Assertions', 'test cases', 'setup/teardown'],
      },
      {
        'id': 'jest',
        'title': 'Jest',
        'tier': 'free',
        'topics': ['Matchers', 'spies', 'async testing'],
      },
      {
        'id': 'mocha',
        'title': 'Mocha',
        'tier': 'free',
        'topics': ['Describe/it', 'hooks (before/after)', 'chai assertions'],
      },
      {
        'id': 'junit',
        'title': 'JUnit',
        'tier': 'free',
        'topics': ['Annotations (@Test)', 'assertions', 'parameterized tests'],
      },
      {
        'id': 'mocks',
        'title': 'Mocks & Stubs',
        'tier': 'vip',
        'topics': ['Sinon', 'test doubles', 'fakes'],
      },
      {
        'id': 'coverage',
        'title': 'Code Coverage',
        'tier': 'vip',
        'topics': ['Istanbul', 'thresholds', 'reports'],
      },
    ],
    "Integration Testing": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Components interaction', 'stubs', 'drivers'],
      },
      {
        'id': 'postman',
        'title': 'Postman',
        'tier': 'free',
        'topics': ['API testing', 'collections', 'environments', 'scripts'],
      },
      {
        'id': 'supertest',
        'title': 'Supertest',
        'tier': 'free',
        'topics': ['Request testing', 'assertions', 'Express integration'],
      },
      {
        'id': 'contracts',
        'title': 'Contract Testing',
        'tier': 'vip',
        'topics': ['Pact', 'consumer/provider', 'verifications'],
      },
      {
        'id': 'api',
        'title': 'API Integration',
        'tier': 'vip',
        'topics': ['Mock servers', 'headers', 'auth'],
      },
      {
        'id': 'db',
        'title': 'Database Integration',
        'tier': 'vip',
        'topics': ['Fixtures', 'seed data', 'transactions'],
      },
    ],
    "End-to-End Testing": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['User flows', 'scenarios', 'headless mode'],
      },
      {
        'id': 'cypress',
        'title': 'Cypress',
        'tier': 'free',
        'topics': ['Commands', 'assertions', 'stubs', 'videos'],
      },
      {
        'id': 'selenium',
        'title': 'Selenium',
        'tier': 'free',
        'topics': ['WebDriver', 'locators', 'waits', 'actions'],
      },
      {
        'id': 'puppeteer',
        'title': 'Puppeteer',
        'tier': 'free',
        'topics': ['Browser control', 'screenshots', 'network interception'],
      },
      {
        'id': 'scenarios',
        'title': 'Test Scenarios',
        'tier': 'vip',
        'topics': ['Happy paths', 'edge cases', 'data-driven'],
      },
      {
        'id': 'automation',
        'title': 'Automation Frameworks',
        'tier': 'vip',
        'topics': ['Playwright', 'Appium', 'cross-browser'],
      },
    ],
    "Test-Driven Development": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Cycle', 'failing tests first', 'minimal code'],
      },
      {
        'id': 'redgreen',
        'title': 'Red-Green-Refactor',
        'tier': 'free',
        'topics': ['Write test', 'make it pass', 'refactor'],
      },
      {
        'id': 'bdd',
        'title': 'Behavior-Driven Development',
        'tier': 'free',
        'topics': ['Cucumber', 'Gherkin', 'features', 'steps'],
      },
      {
        'id': 'mocking',
        'title': 'Mocking in TDD',
        'tier': 'vip',
        'topics': ['Dependencies', 'isolation'],
      },
      {
        'id': 'refactoring',
        'title': 'Refactoring',
        'tier': 'vip',
        'topics': ['Clean code', 'smells', 'patterns'],
      },
      {
        'id': 'tools',
        'title': 'Tools & Best Practices',
        'tier': 'vip',
        'topics': ['Integration with CI', 'coverage goals'],
      },
    ],
    "Web Security": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Threats', 'vulnerabilities', 'mitigations'],
      },
      {
        'id': 'xss',
        'title': 'XSS',
        'tier': 'free',
        'topics': ['Sanitization', 'escaping', 'content security policy'],
      },
      {
        'id': 'csrf',
        'title': 'CSRF',
        'tier': 'free',
        'topics': ['Tokens', 'same-site cookies', 'validation'],
      },
      {
        'id': 'sqlinjection',
        'title': 'SQL Injection',
        'tier': 'free',
        'topics': ['Prepared statements', 'parameterized queries'],
      },
      {
        'id': 'https',
        'title': 'HTTPS & SSL',
        'tier': 'vip',
        'topics': ['Certificates', 'TLS versions', 'HSTS'],
      },
      {
        'id': 'cors',
        'title': 'CORS',
        'tier': 'vip',
        'topics': ['Policies', 'origins', 'headers'],
      },
      {
        'id': 'owasp',
        'title': 'OWASP Top 10',
        'tier': 'vip',
        'topics': ['Injection', 'broken auth', 'sensitive data exposure'],
      },
    ],
    "Performance Optimization": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Bottlenecks', 'profiling', 'benchmarks'],
      },
      {
        'id': 'caching',
        'title': 'Caching',
        'tier': 'free',
        'topics': ['Browser cache', 'server cache', 'Redis/Memcached'],
      },
      {
        'id': 'minification',
        'title': 'Minification & Bundling',
        'tier': 'free',
        'topics': ['Uglify', 'Webpack', 'tree shaking'],
      },
      {
        'id': 'lazy',
        'title': 'Lazy Loading',
        'tier': 'free',
        'topics': ['Images', 'components', 'code splitting'],
      },
      {
        'id': 'cdn',
        'title': 'CDN',
        'tier': 'vip',
        'topics': ['Edge networks', 'static assets', 'geo-distribution'],
      },
      {
        'id': 'profiling',
        'title': 'Profiling Tools',
        'tier': 'vip',
        'topics': ['Chrome DevTools', 'Lighthouse', 'WebPageTest'],
      },
      {
        'id': 'database',
        'title': 'Database Optimization',
        'tier': 'vip',
        'topics': ['Indexes', 'query optimization', 'caching'],
      },
    ],
    "Design Patterns": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Creational', 'structural', 'behavioral'],
      },
      {
        'id': 'singleton',
        'title': 'Singleton',
        'tier': 'free',
        'topics': ['Single instance', 'eager/lazy', 'thread safety'],
      },
      {
        'id': 'factory',
        'title': 'Factory',
        'tier': 'free',
        'topics': ['Abstract factory', 'builder', 'prototype'],
      },
      {
        'id': 'observer',
        'title': 'Observer',
        'tier': 'free',
        'topics': ['Pub/sub', 'event emitters', 'callbacks'],
      },
      {
        'id': 'mvc',
        'title': 'MVC',
        'tier': 'vip',
        'topics': ['Model-view-controller', 'separation of concerns'],
      },
      {
        'id': 'solid',
        'title': 'SOLID Principles',
        'tier': 'vip',
        'topics': [
          'Single responsibility',
          'open-closed',
          'dependency inversion',
        ],
      },
      {
        'id': 'microservices',
        'title': 'Microservices Patterns',
        'tier': 'vip',
        'topics': ['Saga', 'CQRS', 'event sourcing'],
      },
    ],
    "Accessibility & SEO": [
      {
        'id': 'accessibility',
        'title': 'Accessibility Basics',
        'tier': 'free',
        'topics': ['WCAG guidelines', 'screen readers', 'keyboard navigation'],
      },
      {
        'id': 'aria',
        'title': 'ARIA',
        'tier': 'free',
        'topics': ['Roles', 'labels', 'states', 'properties'],
      },
      {
        'id': 'seo',
        'title': 'SEO Basics',
        'tier': 'free',
        'topics': ['On-page factors', 'keywords', 'site speed'],
      },
      {
        'id': 'meta',
        'title': 'Meta Tags',
        'tier': 'free',
        'topics': ['Title', 'description', 'open graph', 'twitter cards'],
      },
      {
        'id': 'semantics',
        'title': 'Semantic Html',
        'tier': 'vip',
        'topics': ['Headings', 'alt text', 'landmarks'],
      },
      {
        'id': 'crawling',
        'title': 'Crawling & Indexing',
        'tier': 'vip',
        'topics': ['Robots.txt', 'sitemaps', 'canonical tags'],
      },
      {
        'id': 'tools',
        'title': 'Tools & Auditing',
        'tier': 'vip',
        'topics': ['WAVE', 'Google Search Console', 'a11y audits'],
      },
    ],
    "Microservices": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': [
          'Monolith vs microservices',
          'decomposition',
          'bounded contexts',
        ],
      },
      {
        'id': 'communication',
        'title': 'Communication',
        'tier': 'free',
        'topics': ['Sync (HTTP)', 'async (messaging)', 'gRPC'],
      },
      {
        'id': 'discovery',
        'title': 'Service Discovery',
        'tier': 'free',
        'topics': ['Eureka', 'Consul', 'registration'],
      },
      {
        'id': 'gateway',
        'title': 'API Gateway',
        'tier': 'free',
        'topics': ['Kong', 'Zuul', 'rate limiting', 'auth'],
      },
      {
        'id': 'resilience',
        'title': 'Resilience Patterns',
        'tier': 'vip',
        'topics': ['Circuit breaker', 'retry', 'bulkhead'],
      },
      {
        'id': 'deployment',
        'title': 'Deployment',
        'tier': 'vip',
        'topics': ['Docker/Kubernetes', 'service mesh (Istio)'],
      },
      {
        'id': 'monitoring',
        'title': 'Monitoring',
        'tier': 'vip',
        'topics': ['Distributed tracing (Jaeger)', 'logs aggregation'],
      },
    ],
    "Real-Time Features": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Bi-directional', 'persistent connections', 'use cases'],
      },
      {
        'id': 'websockets',
        'title': 'WebSockets',
        'tier': 'free',
        'topics': ['Handshakes', 'fallbacks', 'protocols'],
      },
      {
        'id': 'socketio',
        'title': 'Socket.io',
        'tier': 'free',
        'topics': ['Rooms', 'namespaces', 'events', 'broadcasting'],
      },
      {
        'id': 'polling',
        'title': 'Polling & Long Polling',
        'tier': 'free',
        'topics': ['Short/long polling', 'implementation', 'drawbacks'],
      },
      {
        'id': 'sse',
        'title': 'Server-Sent Events',
        'tier': 'vip',
        'topics': ['One-way', 'event streams', 'reconnections'],
      },
      {
        'id': 'pubsub',
        'title': 'Pub/Sub Systems',
        'tier': 'vip',
        'topics': ['RabbitMQ', 'Kafka', 'topics'],
      },
    ],
    "Mobile Integration": [
      {
        'id': 'basics',
        'title': 'Basics',
        'tier': 'free',
        'topics': ['Hybrid vs native', 'responsiveness', 'touch events'],
      },
      {
        'id': 'pwa',
        'title': 'Progressive Web Apps',
        'tier': 'free',
        'topics': [
          'Manifest',
          'service workers',
          'offline support',
          'installable',
        ],
      },
      {
        'id': 'reactnative',
        'title': 'React Native',
        'tier': 'free',
        'topics': ['Components', 'expo', 'navigation', 'state management'],
      },
      {
        'id': 'flutter',
        'title': 'Flutter',
        'tier': 'free',
        'topics': ['Widgets', 'state management', 'providers', 'animations'],
      },
      {
        'id': 'ionic',
        'title': 'Ionic',
        'tier': 'vip',
        'topics': ['Capacitor', 'stencils', 'framework agnostic'],
      },
      {
        'id': 'api',
        'title': 'Mobile APIs',
        'tier': 'vip',
        'topics': ['Responsive APIs', 'mobile-first design', 'cors for mobile'],
      },
      {
        'id': 'push',
        'title': 'Push Notifications',
        'tier': 'vip',
        'topics': ['FCM', 'APNs', 'topics', 'device tokens'],
      },
    ],
    "Emerging Technologies": [
      {
        'id': 'web3',
        'title': 'Web3 & Blockchain',
        'tier': 'free',
        'topics': [
          'Decentralized apps',
          'smart contracts',
          'wallets',
          'Ethereum',
        ],
      },
      {
        'id': 'ai',
        'title': 'AI/ML Integration',
        'tier': 'free',
        'topics': [
          'TensorFlow.js',
          'model training',
          'inference',
          'data pipelines',
        ],
      },
      {
        'id': 'wasm',
        'title': 'WebAssembly',
        'tier': 'free',
        'topics': [
          'Compilation',
          'performance',
          'use cases',
          'Rust integration',
        ],
      },
      {
        'id': 'vrar',
        'title': 'VR/AR',
        'tier': 'free',
        'topics': ['WebVR', 'A-Frame', 'three.js', 'immersive experiences'],
      },
      {
        'id': 'edge',
        'title': 'Edge Computing',
        'tier': 'vip',
        'topics': ['Functions at edge', 'CDNs', 'low latency'],
      },
      {
        'id': 'serverless',
        'title': 'Advanced Serverless',
        'tier': 'vip',
        'topics': ['Lambda@Edge', 'workers', 'event triggers'],
      },
      {
        'id': 'quantum',
        'title': 'Quantum Computing Basics',
        'tier': 'vip',
        'topics': ['Concepts', 'qubits', 'libraries (Qiskit)'],
      },
    ],
  };
}
